apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tomcat-chart.name" . }}
  labels: 
    {{- include "tomcat-chart.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: {{ .Values.spec.replicaCount }}
  selector:
    matchLabels:
      {{- include "tomcat-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tomcat-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: tomcat-container
          image: {{ .Values.spec.image.repository }}:{{ .Values.spec.image.tag }}
          imagePullPolicy: {{ .Values.spec.image.pullPolicy }}
          ports:
            - containerPort: 3000
          resources:
            {{- toYaml .Values.spec.resources | nindent 12 }}
