apiVersion: v1
kind: Service
metadata:
  name: {{ include "tomcat-chart.fullname" . }}
  labels:
    {{- include "tomcat-chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "tomcat-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    {{- include "tomcat-chart.selectorLabels" . | nindent 4 }}
  type: NodePort
