apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    {{- include "tomcat-chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "tomcat-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: tomcat
  type: ClusterIP
